# # NOTE: This file should always be named `repolinter.yml` to allow
# # workflow_dispatch to work properly
# name: Repolinter Action

# # NOTE: This workflow will ONLY check the default branch!
# # Currently there is no elegant way to specify the default
# # branch in the event filtering, so branches are instead
# # filtered in the "Test Default Branch" step.
# on: [push, workflow_dispatch]

# jobs:
#   repolint:
#     name: Run Repolinter
#     runs-on: ubuntu-latest
#     steps:
#       - name: Test Default Branch
#         id: default-branch
#         uses: actions/github-script@v2
#         with:
#           script: |
#             const data = await github.repos.get(context.repo)
#             return data.data && data.data.default_branch === context.ref.split('/').slice(-1)[0]
#       - name: Checkout Self
#         if: ${{ steps.default-branch.outputs.result == 'true' }}
#         uses: actions/checkout@v2
#       - name: Run Repolinter
#         if: ${{ steps.default-branch.outputs.result == 'true' }}
#         uses: newrelic/repolinter-action@v1
#         with:
#           # FIXME: Replace with the appropriate ruleset URL
#           config_url: https://raw.githubusercontent.com/newrelic/.github/main/repolinter-rulesets/new-relic-experimental.yml
#           output_type: issue


name: Deploy to Docker

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # You can also use other runners like `ubuntu-20.04`

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t iamkarans/relicstaurants:v1 .
      
    - name: Push Docker image to Docker Hub
      run: |
        docker push iamkarans/relicstaurants:v1

    - name: Logout from Docker Hub
      run: docker logout
